[REPLICATED-1859] custom preflight checks
replicatedhq/docs pull request #130
Opened 2017-01-27 20:31 UTC by emosbaugh

2017-01-27 23:48 UTC, divolgin approved these changes

2017-01-28 01:33 UTC, wlaoh commented on docs/packaging-an-application/custom-preflight-checks.md
> +flixibility to the point that an arbitrary command can be executed by a vendor provided image. See
flixibility > flexibility

2017-01-28 01:40 UTC, wlaoh requested changes

2017-01-28 01:40 UTC, wlaoh commented on docs/packaging-an-application/custom-preflight-checks.md
> +flixibility to the point that an arbitrary command can be executed by a vendor provided image. See
flixibility > flexibility

2017-01-30 21:56 UTC, wlaoh requested changes

2017-01-30 21:56 UTC, wlaoh commented on docs/packaging-an-application/custom-preflight-checks.md
> +  - status: success
Is this supposed to be success?  I think it's supposed to be warn.

2017-02-09 23:12 UTC, merged