First methods
replicatedhq/docs pull request #171
Opened 2017-03-20 23:57 UTC by stephenlawrence

Added the *First methods to the docs, renamed some deprecated methods to their non-deprecated names

2017-03-21 17:13 UTC, mhald approved these changes

2017-03-21 17:28 UTC, emosbaugh requested changes

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +Template functions that refer to you containers are always addressed in pairs with "component name" and "image name".  You should use the full image name as it appears in your container definition.
that refer to **your** containers

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +{{< template_function name="NodePrivateIpAddress" replicated="true" kubernetes="false" >}}
`NodePrivateIPAddress` <- case sensitive

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +func NodePrivateIpAddress(componentName string, imageName string) string
`NodePrivateIPAddress` <- case sensitive

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +  static_val: '{{repl NodePrivateIpAddress "DB" "redis" }}'
`NodePrivateIPAddress` <- case sensitive

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +{{< template_function name="NodePrivateIpAddressFirst" replicated="true" kubernetes="false" >}}
`NodePrivateIPAddressFirst` <- case sensitive

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +func NodePrivateIpAddressFirst(componentName string, imageName string) string
`NodePrivateIPAddressFirst` <- case sensitive

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +Returns the first node's Private IP Address of Component as a string.
`of a given Component`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +{{< template_function name="NodePrivateIpAddressAll" replicated="true" kubernetes="false" >}}
`NodePrivateIPAddressAll`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +func NodePrivateIpAddressAll(componentName string, imageName string) []string
`NodePrivateIPAddressAll`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +Note: `ContainerExposedPortAll`, `NodePrivateIpAddressAll`, `NodePublicIpAddressAll` are guaranteed to return in the same order
`NodePrivateIPAddressAll` `NodePublicIPAddressAll`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +{{< template_function name="NodePublicIpAddress" replicated="true" kubernetes="false" >}}
`NodePublicIPAddress`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +func NodePublicIpAddress(componentName string, imageName string) string
`NodePublicIPAddressAll`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +  static_val: '{{repl NodePublicIpAddress "DB" "redis" }}'
`NodePublicIPAddress`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +{{< template_function name="NodePublicIpAddressFirst" replicated="true" kubernetes="false" >}}
`NodePublicIPAddressFirst`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +func NodePublicIpAddressFirst(componentName string, imageName string) string
`NodePublicIPAddressFirst`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +Note: `ContainerExposedPortAll`, `NodePrivateIpAddressAll`, `NodePublicIpAddressAll` are guaranteed to return in the same order
I'm unsure about this statement but it should be true.

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +{{< template_function name="NodePublicIpAddressAll" replicated="true" kubernetes="false" >}}
`NodePublicIPAddressAll`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +func NodePublicIpAddressAll(componentName string, imageName string) []string
`NodePublicIPAddressAll`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +Note: `ContainerExposedPortAll`, `NodePrivateIpAddressAll`, `Node PublicIpAddressAll` are guaranteed to return in the same order
`NodePrivateIPAddressAll` `NodePublicIPAddressAll`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +func ContainerExposedPortFirst(componentName string, imagename string, internalPort string) string
`imageName`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
> +Note: `ContainerExposedPortAll`, `NodePrivateIpAddressAll`, `NodePublicIpAddressAll` are guaranteed to return in the same order
`NodePrivateIPAddressAll` `NodePublicIPAddressAll`

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
>  Returns host public IP addresses for all instances of a given Component as an array of strings.
Returns **node** public IP addresses

2017-03-21 17:28 UTC, emosbaugh commented on docs/packaging-an-application/template-functions.md
>  Returns the host public port mapped to the supplied exposed container port for all instances of a given Component as an array of strings.
Returns the **node** public

2017-03-22 00:22 UTC, stephenlawrence commented
Updated with PR fixes. @emosbaugh

2017-03-22 03:13 UTC, emosbaugh approved these changes

2017-03-22 15:10 UTC, merged