help on event sequencing and template function references
replicatedhq/docs pull request #197
Opened 2017-04-26 19:08 UTC by mhald

2017-04-27 19:51 UTC, emosbaugh requested changes

2017-04-27 19:51 UTC, emosbaugh commented on docs/packaging-an-application/events-and-orchestration.md
> +When setting up event orchestration use unique event names and follow the rule of thumb that multiple children are fine but each container should have one parent. Event orchestration is critical for
Should be started?

2017-04-28 15:34 UTC, mhald commented on docs/packaging-an-application/events-and-orchestration.md
> +When setting up event orchestration use unique event names and follow the rule of thumb that multiple children are fine but each container should have one parent. Event orchestration is critical for
Yes, the point here is to ensure the reader knows that for aspects such as discovery of dynamically assigned ports those containers must be started first. There is an exception for template functions that return Replicated-planned information like NodePrivateIPAddressAll. I'll cleanup the language to make it more specific to dynamic content.

2017-04-28 15:54 UTC, emosbaugh approved these changes

2017-04-28 15:55 UTC, merged