Updates for multi-channel licenses
replicatedhq/docs pull request #224
Opened 2017-06-12 18:09 UTC by divolgin

2017-06-12 19:02 UTC, wlaoh requested changes

2017-06-12 19:02 UTC, wlaoh commented on docs/distributing-an-application/create-licenses.md
> +When you create a license you'll need to assign it to at least one release channel (if it is a customer,
`if it is a customer, likely channel is Stable` sounds awkward how about `Stable is a likely channel for customers,`  something along those lines.

2017-06-12 19:02 UTC, wlaoh commented on docs/distributing-an-application/create-licenses.md
> + When license is assigned to multiple channels, the customer will be able to select the channel at install time and later change the release channel in management console.  For airgapped installs, th
`When a license`, `release channel in the management console`

2017-06-12 19:02 UTC, wlaoh commented on docs/kb/supporting-your-customers/multichannel-licenses.md
> +![Invalid License](/static/license-upload-channels.png)
Why is this named `Invalid License`?

2017-06-12 19:02 UTC, wlaoh commented on docs/kb/supporting-your-customers/multichannel-licenses.md
> +For airgapped installations, license channel has to be selected at the time when the airgap bundle is downloaded.
`the license channel`

2017-06-12 19:02 UTC, wlaoh commented on docs/kb/supporting-your-customers/multichannel-licenses.md
> +Channel can be changed on the License page in Replicated management console.  Once channel is  changed, Replicated will sync license and check for release updates.  If newer releases are available, t
Extra space between `is` and `changed`

2017-06-13 20:22 UTC, divolgin commented on docs/kb/supporting-your-customers/multichannel-licenses.md
> +Channel can be changed on the License page in Replicated management console.  Once channel is  changed, Replicated will sync license and check for release updates.  If newer releases are available, t
Who cares! It's HTML! :)

2017-06-14 21:18 UTC, merged