entrypoint override
replicatedhq/docs pull request #43
Opened 2016-09-14 23:02 UTC by mhald

2016-09-14 23:06 UTC, emosbaugh commented on docs/packaging-an-application/components-and-containers.md
> +For third party containers the entrypoint the container comes with may be too strict.  To include such containers the entrypoint can be overwritten using exec entrypoint form which takes an list.
why dont you revise this sentence and ill look again.

2016-09-14 23:07 UTC, emosbaugh requested changes
please review

2016-09-14 23:31 UTC, emosbaugh commented on docs/packaging-an-application/components-and-containers.md
> +cases use the entrypoint option to override the provided container entry point.
i would just mention that it expects an array

2016-09-14 23:31 UTC, emosbaugh requested changes
changes requested

2016-09-15 00:04 UTC, emosbaugh approved these changes

2016-09-19 23:52 UTC, marccampbell commented on docs/packaging-an-application/components-and-containers.md
> +cases use the entrypoint option to override the provided container entry point.
I don't understand "entry point is too strict".  This feature is useful for other use cases, such as reusing an image but not running the executable in the entrypoint, right?  Should this sentence remain?

2016-09-21 17:29 UTC, merged