volumes from
replicatedhq/docs pull request #47
Opened 2016-09-15 18:07 UTC by mhald

2016-09-15 18:08 UTC, emosbaugh commented on docs/packaging-an-application/components-and-containers.md
> +```yml:
im not used to seeing a colon here

2016-09-15 18:11 UTC, emosbaugh commented on docs/packaging-an-application/components-and-containers.md
> +The container using "volumes from" must start after any containers it mounts from.  Volumes from takes an array of
`The container using  "volumes_from" must start after any containers it mounts from.  Property "volumes_from" takes...`

2016-09-15 18:11 UTC, emosbaugh requested changes
couple of comments

2016-09-15 18:18 UTC, emosbaugh commented on docs/packaging-an-application/components-and-containers.md
> +The container using "volumes from" must start after any containers it mounts from.  Property "volumes from" takes an array of
`"volumes from" != "volumes_from"`

2016-09-15 18:55 UTC, emosbaugh approved these changes

2016-09-19 23:49 UTC, marccampbell commented on docs/packaging-an-application/components-and-containers.md
> +We can use "volumes_from" to attach several mounts from a colocated container.
Can this become:

"Replicated supports `volumes_from` to attach several mounts from a colocated container."?

2016-09-21 16:57 UTC, merged